version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 905418222419.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ocm-image .
      - echo "Tagging Docker image..."
      - docker tag ocm-image:latest 905418222419.dkr.ecr.us-west-2.amazonaws.com/online-course-management-ecr:latest
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 905418222419.dkr.ecr.us-west-2.amazonaws.com/online-course-management-ecr:latest
