apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Cluster
  region: us-east-1

vpc:
  id: vpc-00c23124ac777770b
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0af4795d95cb2cbb2
      my-new-stack-PublicSubnet02:
        id: subnet-0c4ecb160e6e4fb7e
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-042e01f01ec929428
      my-new-stack-PrivateSubnet02:
        id: subnet-0c0d0bba610bdcc4f

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true