apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 905418222419.dkr.ecr.us-west-2.amazonaws.com/online-course-management-ecr:latest
          ports:
            - containerPort: 8501