apiVersion: v1
kind: Service
metadata:
  name: online-course-management-service
spec:
  selector:
    app: online-course-management
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer
